import { Inter } from "next/font/google";
import "@/assets/styles/globals.css";
import "react-quill/dist/quill.snow.css";
import { ReduxProvider } from "@/libs/redux/provider";

export const metadata = {
  title: "Plantopia",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
